function b = out4Filter
%UNTITLED Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 24-Jul-2018 12:23:29

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 4;  % Sampling Frequency

Fpass = 0.2;             % Passband Frequency
Fstop = 0.8;             % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 1e-05;           % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);
% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
end
